### ISSUE TITLE
Hard to tell how I'm doing against multiple examples

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/function-arguments-lab#1]
<img width="728" alt="screen shot 2018-04-01 at 3 09 18 pm" src="https://user-images.githubusercontent.com/13033515/38176526-ab46f364-35be-11e8-9f30-2df7a9d72004.png">
 It's not clear how I did on examples 1 and 2, just the third on.

Using `print` here would make it clearer:
<img width="739" alt="screen shot 2018-04-01 at 3 09 47 pm" src="https://user-images.githubusercontent.com/13033515/38176529-c0c8dc3e-35be-11e8-8b10-680c5123d867.png">

@JeffKatzy

**Comment by tkoar** [comment]
The lab has been updated so that each of the function calls are in separate cells so the output can be seen for each example.
