### ISSUE TITLE
Tests Won't Pass

### ISSUE THREAD

**Issue by tjcarney89** [learn-co-curriculum/function-arguments-lab#3]
I've completed all of the functions for the Functions with Arguments Lab and all of the outputs match the required outputs. I tried deleting my fork and reloading the lab, but the tests still do not pass. 

I'm using Google Chrome on a MacBook Air.

**Comment by tkoar** [comment]
The tests have been updated to match this lab in re: #5 . If you would like to re-delete your fork and run the tests again, they should pass given your solution is accurate. Thanks!
