### ISSUE TITLE
"#high_rating" method requirements are vague

### ISSUE THREAD

**Issue by mikeappell** [learn-co-curriculum/function-arguments-lab#4]
The description for creating the "#high_rating" method is as follows:
```
Now write a function called high_rating that takes a restaurant as a first argument and
a rating (in the form of a number) as the second argument.
```
However, it isn't clear exactly what the requirement for the method is. Is it supposed to compare the restaurant's rating to the rating passed in and see if it's higher? That's what I'm assuming, but it's vague.

**Comment by tkoar** [comment]
Thank you! The phrasing has been updated to add more clarity to the directions for this function.
