### ISSUE TITLE
Typos in instructions

### ISSUE THREAD

**Issue by jczerepinski** [learn-co-curriculum/function-arguments-lab#6]
In the sentence "Now let's write a function called `is_cheaper` that returns `True` if a restaurant has a **higher** price, that is the **restaurnat** has more `'$'` signs, than an alternative restaurant."

Shouldn't "higher" be lower? Also, 'restaurant' is misspelled.

**Comment by cutterbuck** [comment]
thanks for pointing that out, @jczerepinski !
