### ISSUE TITLE
Typo in instructions or in expected answer

### ISSUE THREAD

**Issue by jczerepinski** [learn-co-curriculum/function-arguments-lab#7]
For the exercise "returns True if the given restaurant's rating is greater than or equal to the provided rating and returns False otherwise", 

"high_rating(frontier_restaurant, 4)" is marked with the answer of False. The directions specify it was greater than or equal to. The answer is equal to as it's 4, so the answer should be True.

**Comment by cutterbuck** [comment]
good catch!
